/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103272-g7bba0dd638-20210817"
#endif /* AVUTIL_FFVERSION_H */
